import { useMemo, useEffect, useState, useRef } from "react";
import { apiClient } from "../lib/api";
import type { Session, Message } from "../types";

const isAutoGeneratedName = (name: string) => {
  return /^\d{4}-\d{2}-\d{2}T/.test(name);
};

interface ResolveOptions {
  resolveNames?: boolean;
  maxResolveSessions?: number;
  resolveBatchSize?: number;
  resolveBatchDelayMs?: number;
}

export function useResolvedSessions(
  sessions: Session[] | undefined,
  enabled = true,
  options: ResolveOptions = {}
) {
  const {
    resolveNames = true,
    maxResolveSessions = 20,
    resolveBatchSize = 3,
    resolveBatchDelayMs = 300,
  } = options;
  const resolveInFlightRef = useRef(false);

  const [resolvedNames, setResolvedNames] = useState<Map<string, string>>(
    () => new Map()
  );
  const [resolvedIds, setResolvedIds] = useState<Set<string>>(() => new Set());

  const sessionsToResolve = useMemo(() => {
    if (!resolveNames) return [] as Session[];
    return (sessions || [])
      .filter((s) => isAutoGeneratedName(s.name) && !resolvedIds.has(s.id))
      .sort(
        (a, b) =>
          new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
      )
      .slice(0, maxResolveSessions);
  }, [sessions, resolvedIds, resolveNames, maxResolveSessions]);

  useEffect(() => {
    if (!enabled) return;
    if (!resolveNames) return;
    if (sessionsToResolve.length === 0) return;
    if (resolveInFlightRef.current) return;

    resolveInFlightRef.current = true;
    let isCancelled = false;

    const fetchNames = async () => {
      for (let i = 0; i < sessionsToResolve.length; i += resolveBatchSize) {
        if (isCancelled) return;
        const batch = sessionsToResolve.slice(i, i + resolveBatchSize);
        const results = await Promise.all(
          batch.map(async (session) => {
            try {
              const messages = await apiClient.get<Message[]>(
                `/api/sessions/${session.id}/messages?limit=1&direction=head`
              );
              const firstUserMessage = messages.find((m) => m.role === "user");
              return {
                id: session.id,
                name: firstUserMessage
                  ? firstUserMessage.content.slice(0, 60) +
                    (firstUserMessage.content.length > 60 ? "..." : "")
                  : null,
              };
            } catch {
              return { id: session.id, name: null };
            }
          })
        );

        setResolvedNames((prev) => {
          const next = new Map(prev);
          results.forEach((result) => {
            if (result.name) {
              next.set(result.id, result.name);
            }
          });
          return next;
        });
        setResolvedIds((prev) => {
          const next = new Set(prev);
          results.forEach((result) => {
            next.add(result.id);
          });
          return next;
        });

        if (i + resolveBatchSize < sessionsToResolve.length) {
          await new Promise((resolve) => setTimeout(resolve, resolveBatchDelayMs));
        }
      }
    };

    fetchNames().finally(() => {
      if (!isCancelled) {
        resolveInFlightRef.current = false;
      }
    });

    return () => {
      isCancelled = true;
      resolveInFlightRef.current = false;
    };
  }, [enabled, resolveNames, sessionsToResolve, resolveBatchSize, resolveBatchDelayMs]);

  return useMemo(() => {
    if (!sessions) return undefined;
    return sessions.map((session) => {
      if (resolvedNames.has(session.id)) {
        return { ...session, name: resolvedNames.get(session.id)! };
      }
      return session;
    });
  }, [sessions, resolvedNames]);
}
