import { useMemo, useEffect, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { apiClient } from "../lib/api";
import type { Session, Message } from "../types";

// Helper to check if a name matches the auto-generated timestamp pattern
const isAutoGeneratedName = (name: string) => {
  return /^\d{4}-\d{2}-\d{2}T/.test(name);
};

export function useSessions() {
  const sessionsQuery = useQuery<Session[]>({
    queryKey: ["sessions"],
    queryFn: () => apiClient.get<Session[]>("/api/sessions"),
    // Reduce refetch frequency to prevent re-render storms
    staleTime: 30000, // 30 seconds
    refetchInterval: 60000, // Only poll every minute
  });

  // Store resolved names in local state with persistent cache
  const [resolvedNames, setResolvedNames] = useState<Map<string, string>>(
    () => new Map()
  );

  // Identify sessions that need name resolution
  // Optimization: Limit to 5 most recent sessions to reduce parallel requests.
  // Uses Promise.all for a single batch fetch instead of staggered useQueries,
  // eliminating the 500ms waterfall (was 10 requests × 50ms stagger).
  const sessionsToResolve = useMemo(() => {
    return (sessionsQuery.data || [])
      .filter((s) => isAutoGeneratedName(s.name) && !resolvedNames.has(s.id))
      .sort(
        (a, b) =>
          new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
      )
      .slice(0, 5);
  }, [sessionsQuery.data, resolvedNames]);

  // Batch fetch first messages for sessions needing name resolution
  useEffect(() => {
    if (sessionsToResolve.length === 0) return;

    const fetchNames = async () => {
      const results = await Promise.all(
        sessionsToResolve.map(async (session) => {
          try {
            const messages = await apiClient.get<Message[]>(
              `/api/sessions/${session.id}/messages?limit=1&direction=head`
            );
            const firstUserMessage = messages.find((m) => m.role === "user");
            return {
              id: session.id,
              name: firstUserMessage
                ? firstUserMessage.content.slice(0, 60) +
                  (firstUserMessage.content.length > 60 ? "..." : "")
                : null,
            };
          } catch {
            return { id: session.id, name: null };
          }
        })
      );

      setResolvedNames((prev) => {
        const next = new Map(prev);
        results.forEach((r) => {
          if (r.name) {
            next.set(r.id, r.name);
          }
        });
        return next;
      });
    };

    fetchNames();
  }, [sessionsToResolve]);

  // Return sessions with resolved names - memoized to prevent unnecessary re-renders
  const enhancedSessions = useMemo(() => {
    if (!sessionsQuery.data) return undefined;
    return sessionsQuery.data.map((session) => {
      if (resolvedNames.has(session.id)) {
        return { ...session, name: resolvedNames.get(session.id)! };
      }
      return session;
    });
  }, [sessionsQuery.data, resolvedNames]);

  return {
    ...sessionsQuery,
    data: enhancedSessions,
  };
}
