import { useMemo, useEffect, useState, useRef } from "react";
import { useQuery } from "@tanstack/react-query";
import { apiClient } from "../lib/api";
import type { Session, Message } from "../types";

// Helper to check if a name matches the auto-generated timestamp pattern
const isAutoGeneratedName = (name: string) => {
  return /^\d{4}-\d{2}-\d{2}T/.test(name);
};

export function useSessions(
  enabled = true,
  options: { resolveNames?: boolean } = {}
) {
  const { resolveNames = true } = options;
  const maxResolveSessions = 20;
  const resolveBatchSize = 3;
  const resolveBatchDelayMs = 300;
  const resolveInFlightRef = useRef(false);

  const sessionsQuery = useQuery<Session[]>({
    queryKey: ["sessions"],
    queryFn: () => apiClient.get<Session[]>("/api/sessions"),
    enabled,
    // Reduce refetch frequency to prevent re-render storms
    staleTime: 30000, // 30 seconds
    refetchInterval: 60000, // Only poll every minute
    refetchIntervalInBackground: false,
    refetchOnWindowFocus: false,
    refetchOnReconnect: false,
  });

  // Store resolved names in local state with persistent cache
  const [resolvedNames, setResolvedNames] = useState<Map<string, string>>(
    () => new Map()
  );
  const [resolvedIds, setResolvedIds] = useState<Set<string>>(() => new Set());

  // Identify sessions that need name resolution
  const sessionsToResolve = useMemo(() => {
    if (!resolveNames) return [] as Session[];
    return (sessionsQuery.data || [])
      .filter(
        (s) => isAutoGeneratedName(s.name) && !resolvedIds.has(s.id)
      )
      .sort(
        (a, b) =>
          new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
      )
      .slice(0, maxResolveSessions);
  }, [sessionsQuery.data, resolvedIds, resolveNames]);

  // Batch fetch first messages for sessions needing name resolution
  useEffect(() => {
    if (!enabled) return;
    if (!resolveNames) return;
    if (sessionsToResolve.length === 0) return;
    if (resolveInFlightRef.current) return;

    resolveInFlightRef.current = true;
    let isCancelled = false;

    const fetchNames = async () => {
      for (let i = 0; i < sessionsToResolve.length; i += resolveBatchSize) {
        if (isCancelled) return;
        const batch = sessionsToResolve.slice(i, i + resolveBatchSize);
        const results = await Promise.all(
          batch.map(async (session) => {
            try {
              const messages = await apiClient.get<Message[]>(
                `/api/sessions/${session.id}/messages?limit=1&direction=head`
              );
              const firstUserMessage = messages.find((m) => m.role === "user");
              return {
                id: session.id,
                name: firstUserMessage
                  ? firstUserMessage.content.slice(0, 60) +
                    (firstUserMessage.content.length > 60 ? "..." : "")
                  : null,
              };
            } catch {
              return { id: session.id, name: null };
            }
          })
        );

        setResolvedNames((prev) => {
          const next = new Map(prev);
          results.forEach((r) => {
            if (r.name) {
              next.set(r.id, r.name);
            }
          });
          return next;
        });
        setResolvedIds((prev) => {
          const next = new Set(prev);
          results.forEach((r) => {
            next.add(r.id);
          });
          return next;
        });
        if (i + resolveBatchSize < sessionsToResolve.length) {
          await new Promise((resolve) => setTimeout(resolve, resolveBatchDelayMs));
        }
      }
    };

    fetchNames().finally(() => {
      if (!isCancelled) {
        resolveInFlightRef.current = false;
      }
    });
    return () => {
      isCancelled = true;
      resolveInFlightRef.current = false;
    };
  }, [enabled, sessionsToResolve, resolveNames]);

  // Return sessions with resolved names - memoized to prevent unnecessary re-renders
  const enhancedSessions = useMemo(() => {
    if (!sessionsQuery.data) return undefined;
    return sessionsQuery.data.map((session) => {
      if (resolvedNames.has(session.id)) {
        return { ...session, name: resolvedNames.get(session.id)! };
      }
      return session;
    });
  }, [sessionsQuery.data, resolvedNames]);

  return {
    ...sessionsQuery,
    data: enhancedSessions,
  };
}
