import { useState, useMemo, useRef, useEffect } from "react";
import { Search, X, Loader2, Clock, Star, MessageSquare } from "lucide-react";
import { Dialog, DialogContent, DialogTitle } from "./ui/dialog";
import { Input } from "./ui/input";
import { Badge } from "./ui/badge";
import { cn } from "../lib/utils";
import { useKeyboardNavigation } from "../hooks/useCommandPalette";
import type { Session } from "../types";

interface CommandPaletteProps {
  isOpen: boolean;
  onClose: () => void;
  sessions: Session[];
  recentSessionIds: string[];
  favoriteSessionIds: string[];
  currentSessionId: string | null;
  activeSessionIds: Set<string>;
  thinkingSessionIds: Set<string>;
  unreadSessions: Set<string>;
  onSelectSession: (sessionId: string) => void;
}

// Fuzzy search implementation
function fuzzySearch(query: string, text: string): boolean {
  const queryLower = query.toLowerCase();
  const textLower = text.toLowerCase();

  let queryIndex = 0;
  let textIndex = 0;

  while (queryIndex < queryLower.length && textIndex < textLower.length) {
    if (queryLower[queryIndex] === textLower[textIndex]) {
      queryIndex++;
    }
    textIndex++;
  }

  return queryIndex === queryLower.length;
}

// Format date for display
const formatDate = (dateString: string) => {
  try {
    return new Intl.DateTimeFormat("en-US", {
      month: "short",
      day: "numeric",
      hour: "numeric",
      minute: "2-digit",
    }).format(new Date(dateString));
  } catch {
    return dateString;
  }
};

// Check if name is auto-generated timestamp
const isAutoGeneratedName = (name: string) => {
  return /^\d{4}-\d{2}-\d{2}T/.test(name);
};

interface SessionWithMeta {
  session: Session;
  isRecent: boolean;
  isFavorite: boolean;
  isActive: boolean;
  isThinking: boolean;
  isUnread: boolean;
  score: number;
}

export function CommandPalette({
  isOpen,
  onClose,
  sessions,
  recentSessionIds,
  favoriteSessionIds,
  currentSessionId,
  activeSessionIds,
  thinkingSessionIds,
  unreadSessions,
  onSelectSession,
}: CommandPaletteProps) {
  const [searchQuery, setSearchQuery] = useState("");

  // Filter and sort sessions
  const filteredSessions = useMemo(() => {
    if (!sessions) return [];

    const recentSet = new Set(recentSessionIds);
    const favoriteSet = new Set(favoriteSessionIds);

    let scoredSessions: SessionWithMeta[] = sessions.map((session) => {
      const isRecent = recentSet.has(session.id);
      const isFavorite = favoriteSet.has(session.id);
      const isActive = activeSessionIds.has(session.id) || session.is_active;
      const isThinking = thinkingSessionIds.has(session.id);
      const isUnread = unreadSessions.has(session.id);

      // Calculate score for sorting
      let score = 0;
      if (isFavorite) score += 100;
      if (isRecent) score += 50;
      if (isActive) score += 30;
      if (isUnread) score += 20;
      if (currentSessionId === session.id) score -= 10; // Deprioritize current

      return {
        session,
        isRecent,
        isFavorite,
        isActive,
        isThinking,
        isUnread,
        score,
      };
    });

    // Apply fuzzy search if query exists
    if (searchQuery.trim()) {
      scoredSessions = scoredSessions.filter((item) => {
        const searchText = `${item.session.name} ${item.session.project_path}`;
        return fuzzySearch(searchQuery, searchText);
      });
    }

    // Sort by score (descending), then by most recently created
    scoredSessions.sort((a, b) => {
      if (b.score !== a.score) return b.score - a.score;
      return new Date(b.session.created_at).getTime() - new Date(a.session.created_at).getTime();
    });

    return scoredSessions;
  }, [
    sessions,
    recentSessionIds,
    favoriteSessionIds,
    activeSessionIds,
    thinkingSessionIds,
    unreadSessions,
    currentSessionId,
    searchQuery,
  ]);

  // Handle selection
  const handleSelect = (session: Session) => {
    onSelectSession(session.id);
    onClose();
  };

  // Keyboard navigation
  const { selectedIndex } = useKeyboardNavigation({
    items: filteredSessions,
    onSelect: (item) => handleSelect(item.session),
    getItemId: (item) => item.session.id,
    enabled: isOpen,
  });

  // Scroll selected item into view
  const selectedRef = useRef<HTMLButtonElement>(null);
  useEffect(() => {
    if (selectedRef.current) {
      selectedRef.current.scrollIntoView({ block: "nearest", behavior: "smooth" });
    }
  }, [selectedIndex]);

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="p-0 gap-0 overflow-hidden sm:!max-w-2xl sm:!w-[calc(100vw-2rem)] [&>button:last-child]:hidden">
        <DialogTitle className="sr-only">Switch Session</DialogTitle>

        {/* Search header */}
        <div className="flex items-center gap-2 px-3 py-3 border-b">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              autoFocus
              type="text"
              placeholder="Search sessions... (Cmd+K)"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-9 pr-9 h-11 text-base"
            />
            {searchQuery && (
              <button
                onClick={() => setSearchQuery("")}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground transition-colors"
              >
                <X className="h-4 w-4" />
              </button>
            )}
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg hover:bg-muted transition-colors sm:hidden"
          >
            <X className="h-5 w-5 text-muted-foreground" />
          </button>
          <kbd className="hidden sm:inline-flex h-6 items-center gap-1 rounded border bg-muted px-2 font-mono text-xs text-muted-foreground">
            ESC
          </kbd>
        </div>

        {/* Results list */}
        <div className="max-h-[60vh] overflow-y-auto">
          {filteredSessions.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-12 text-muted-foreground">
              <MessageSquare className="h-12 w-12 mb-3 opacity-30" />
              <p className="text-sm font-medium">
                {searchQuery ? "No sessions found" : "No sessions available"}
              </p>
              {searchQuery && (
                <p className="text-xs mt-1">Try adjusting your search</p>
              )}
            </div>
          ) : (
            <div className="py-2">
              {/* Section headers when no search */}
              {!searchQuery && (
                <div className="px-4 py-1.5 text-xs font-medium text-muted-foreground uppercase tracking-wider">
                  {filteredSessions.some((s) => s.isFavorite)
                    ? "Favorites & Recent"
                    : filteredSessions.some((s) => s.isRecent)
                      ? "Recent Sessions"
                      : "All Sessions"}
                </div>
              )}

              {filteredSessions.map((item, index) => {
                const { session, isRecent, isFavorite, isActive, isThinking, isUnread } = item;
                const isSelected = index === selectedIndex;
                const isCurrent = currentSessionId === session.id;
                const isAutoName = isAutoGeneratedName(session.name);

                const title = isAutoName
                  ? formatDate(session.created_at)
                  : session.name || "Untitled Session";

                return (
                  <button
                    key={session.id}
                    ref={isSelected ? selectedRef : null}
                    onClick={() => handleSelect(session)}
                    className={cn(
                      "w-full flex items-center gap-3 px-4 py-2.5 text-left transition-colors",
                      isSelected ? "bg-accent" : "hover:bg-muted/50"
                    )}
                  >
                    {/* Status/Type icon */}
                    <div className="relative shrink-0">
                      {isFavorite ? (
                        <Star className="h-4 w-4 text-primary fill-primary" />
                      ) : isRecent ? (
                        <Clock className="h-4 w-4 text-muted-foreground" />
                      ) : (
                        <MessageSquare className="h-4 w-4 text-muted-foreground" />
                      )}

                      {/* Active indicator */}
                      {isActive && (
                        <span className="absolute -top-0.5 -right-0.5 w-2 h-2 rounded-full bg-success border border-background" />
                      )}
                    </div>

                    {/* Session info */}
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2">
                        <span className="font-medium text-sm truncate">{title}</span>
                        {isCurrent && (
                          <Badge variant="secondary" className="text-xs shrink-0">
                            Current
                          </Badge>
                        )}
                        {isUnread && (
                          <Badge className="h-2 w-2 p-0 rounded-full bg-accent hover:bg-accent border-none shrink-0" />
                        )}
                      </div>
                      <div className="text-xs text-muted-foreground truncate">
                        {session.project_path}
                      </div>
                    </div>

                    {/* Right side indicators */}
                    <div className="flex items-center gap-2 shrink-0">
                      {isThinking && (
                        <Loader2 className="h-4 w-4 animate-spin text-primary" />
                      )}
                      <span className="text-xs text-muted-foreground">
                        {formatDate(session.created_at)}
                      </span>
                    </div>
                  </button>
                );
              })}
            </div>
          )}
        </div>

        {/* Footer with keyboard hints */}
        <div className="hidden sm:flex items-center justify-between px-4 py-2 border-t bg-muted/30 text-xs text-muted-foreground">
          <div className="flex items-center gap-4">
            <span className="flex items-center gap-1">
              <kbd className="rounded border bg-background px-1.5 py-0.5 font-mono">↑↓</kbd>
              Navigate
            </span>
            <span className="flex items-center gap-1">
              <kbd className="rounded border bg-background px-1.5 py-0.5 font-mono">↵</kbd>
              Select
            </span>
          </div>
          <div className="flex items-center gap-3">
            <span className="flex items-center gap-1">
              <span className="w-2 h-2 rounded-full bg-success" />
              Active
            </span>
            <span className="flex items-center gap-1">
              <Star className="h-3 w-3 text-primary fill-primary" />
              Favorite
            </span>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
