import { useState } from "react";
import { Loader2, MessageSquare, Calendar, Star, Pin } from "lucide-react";
import { Badge } from "./ui/badge";
import { cn } from "../lib/utils";
import type { Session } from "../types";

interface SessionItemProps {
  session: Session;
  isSelected: boolean;
  isActive: boolean;
  isThinking: boolean;
  isUnread: boolean;
  isFavorite?: boolean;
  isCompact?: boolean;
  firstMessagePreview?: string;
  onClick: () => void;
  onToggleFavorite?: () => void;
  showFavoriteButton?: boolean;
}

// Helper to check if a name matches the auto-generated timestamp pattern
const isAutoGeneratedName = (name: string) => {
  return /^\d{4}-\d{2}-\d{2}T/.test(name);
};

const formatDate = (dateString: string) => {
  try {
    return new Intl.DateTimeFormat("en-US", {
      month: "short",
      day: "numeric",
      hour: "numeric",
      minute: "2-digit",
    }).format(new Date(dateString));
  } catch {
    return dateString;
  }
};

// Get initials from session name or use a default
const getSessionInitials = (session: Session): string => {
  if (isAutoGeneratedName(session.name)) {
    return "#";
  }
  const words = session.name.split(" ");
  if (words.length === 1) {
    return words[0].slice(0, 2).toUpperCase();
  }
  return (words[0][0] + words[words.length - 1][0]).toUpperCase();
};

// Get a consistent color for a session based on its ID
const getSessionColor = (sessionId: string): string => {
  const colors = [
    "bg-blue-500/20 text-blue-600 border-blue-500/30",
    "bg-green-500/20 text-green-600 border-green-500/30",
    "bg-purple-500/20 text-purple-600 border-purple-500/30",
    "bg-orange-500/20 text-orange-600 border-orange-500/30",
    "bg-pink-500/20 text-pink-600 border-pink-500/30",
    "bg-cyan-500/20 text-cyan-600 border-cyan-500/30",
    "bg-amber-500/20 text-amber-600 border-amber-500/30",
    "bg-indigo-500/20 text-indigo-600 border-indigo-500/30",
  ];
  let hash = 0;
  for (let i = 0; i < sessionId.length; i++) {
    hash = sessionId.charCodeAt(i) + ((hash << 5) - hash);
  }
  return colors[Math.abs(hash) % colors.length];
};

export function SessionItem({
  session,
  isSelected,
  isActive,
  isThinking,
  isUnread,
  isFavorite = false,
  isCompact = false,
  firstMessagePreview,
  onClick,
  onToggleFavorite,
  showFavoriteButton = false,
}: SessionItemProps) {
  const [showPreview, setShowPreview] = useState(false);
  const isAutoName = isAutoGeneratedName(session.name);

  const title = isAutoName ? formatDate(session.created_at) : session.name || "Untitled Session";
  const subtitle = isAutoName ? `ID: ${session.id.substring(0, 8)}...` : formatDate(session.created_at);
  const initials = getSessionInitials(session);
  const colorClass = getSessionColor(session.id);

  if (isCompact) {
    return (
      <div className="relative group">
        <button
          onClick={onClick}
          className={cn(
            "w-full flex items-center justify-center p-2 rounded-lg transition-all",
            "border-2",
            isSelected
              ? "bg-accent text-accent-foreground border-primary shadow-sm"
              : "bg-card border-transparent hover:border-primary/30 hover:shadow-sm"
          )}
          title={title}
        >
          <div
            className={cn(
              "w-8 h-8 rounded-md flex items-center justify-center text-xs font-bold border",
              colorClass
            )}
          >
            {initials}
          </div>

          {/* Status indicator dot */}
          {isActive && (
            <div className="absolute -top-0.5 -right-0.5 w-2.5 h-2.5 rounded-full bg-success border-2 border-background shadow-sm" />
          )}

          {/* Thinking indicator */}
          {isThinking && (
            <div className="absolute -bottom-0.5 -right-0.5">
              <Loader2 className="h-3 w-3 animate-spin text-primary" />
            </div>
          )}

          {/* Unread indicator */}
          {isUnread && (
            <div className="absolute top-0.5 left-0.5 w-2 h-2 rounded-full bg-accent border border-background" />
          )}
        </button>

        {/* Tooltip */}
        <div className="absolute left-full ml-2 top-1/2 -translate-y-1/2 opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none z-50">
          <div className="bg-popover text-popover-foreground px-3 py-2 rounded-lg shadow-lg border text-sm whitespace-nowrap">
            <div className="font-medium">{title}</div>
            <div className="text-xs text-muted-foreground">{subtitle}</div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div
      className="relative group"
      onMouseEnter={() => firstMessagePreview && setShowPreview(true)}
      onMouseLeave={() => setShowPreview(false)}
    >
      <button
        onClick={onClick}
        className={cn(
          "w-full flex items-start gap-3 px-3 py-2.5 text-left rounded-lg transition-all",
          "border",
          isSelected
            ? "bg-accent/80 text-accent-foreground border-primary shadow-sm"
            : "bg-card/50 border-transparent hover:bg-card hover:border-border/50 hover:shadow-sm"
        )}
      >
        {/* Avatar/Initials */}
        <div
          className={cn(
            "w-8 h-8 rounded-md flex items-center justify-center text-xs font-bold border shrink-0 mt-0.5",
            colorClass
          )}
        >
          {initials}
        </div>

        {/* Session info */}
        <div className="flex-1 min-w-0">
          <div className="flex items-center justify-between gap-2">
            <span
              className={cn(
                "truncate font-medium text-sm leading-tight",
                isSelected ? "text-accent-foreground" : "text-foreground"
              )}
            >
              {title}
            </span>
            <div className="flex items-center gap-1 shrink-0">
              {isFavorite && <Pin className="h-3 w-3 text-primary" />}
              {isUnread && (
                <Badge className="h-2 w-2 p-0 rounded-full bg-accent hover:bg-accent border-none" />
              )}
            </div>
          </div>

          <div
            className={cn(
              "flex items-center gap-1.5 text-xs mt-0.5",
              isSelected ? "text-accent-foreground/70" : "text-muted-foreground"
            )}
          >
            {isActive ? (
              <span className="flex items-center gap-1">
                <span className="w-1.5 h-1.5 rounded-full bg-success" />
                Active
              </span>
            ) : isThinking ? (
              <span className="flex items-center gap-1">
                <Loader2 className="h-3 w-3 animate-spin" />
                Thinking...
              </span>
            ) : (
              <>
                {isAutoName ? (
                  <Calendar className="h-3 w-3" />
                ) : (
                  <MessageSquare className="h-3 w-3" />
                )}
                <span className="truncate">{subtitle}</span>
              </>
            )}
          </div>
        </div>

        {/* Favorite button (visible on hover) */}
        {showFavoriteButton && onToggleFavorite && (
          <button
            onClick={(e) => {
              e.stopPropagation();
              onToggleFavorite();
            }}
            className={cn(
              "opacity-0 group-hover:opacity-100 transition-opacity p-1 rounded hover:bg-background/50",
              isFavorite && "opacity-100"
            )}
          >
            <Star
              className={cn("h-3.5 w-3.5", isFavorite ? "fill-primary text-primary" : "text-muted-foreground")}
            />
          </button>
        )}
      </button>

      {/* Preview tooltip */}
      {showPreview && firstMessagePreview && (
        <div className="absolute left-0 right-0 top-full mt-1 z-50">
          <div className="bg-popover text-popover-foreground px-3 py-2 rounded-lg shadow-lg border text-xs">
            <div className="text-muted-foreground mb-1">Last message:</div>
            <div className="line-clamp-2">{firstMessagePreview}</div>
          </div>
        </div>
      )}
    </div>
  );
}
