import { useState } from "react";
import { useSessions } from "../hooks/useSessions";
import { useProjects } from "../hooks/useProjects";
import { useAppStore } from "../store/appStore";
import { useStartSession } from "../hooks/useStartSession";
import { ScrollArea } from "./ui/scroll-area";
import { NewSessionDialog } from "./NewSessionDialog";
import { ProjectManager } from "./ProjectManager";
import { Badge } from "./ui/badge";
import { Button } from "./ui/button";
import { Loader2, ChevronDown, ChevronRight, MessageSquare, Calendar } from "lucide-react";
import { cn } from "../lib/utils";
import type { Session } from "../types";

interface SessionListProps {
  className?: string;
}

const DEFAULT_SESSION_LIMIT = 5;

// Helper to check if a name matches the auto-generated timestamp pattern
// e.g., 2026-01-08T01-21-05-615Z_ed05b...
const isAutoGeneratedName = (name: string) => {
  return /^\d{4}-\d{2}-\d{2}T/.test(name);
};

const formatDate = (dateString: string) => {
  try {
    return new Intl.DateTimeFormat('en-US', {
      month: 'short',
      day: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
    }).format(new Date(dateString));
  } catch {
    return dateString;
  }
};

export function SessionList({ className }: SessionListProps) {
  const { data: sessions, isLoading: sessionsLoading } = useSessions();
  const { data: projects, isLoading: projectsLoading } = useProjects();
  const currentSessionId = useAppStore((state) => state.currentSessionId);
  const setCurrentSession = useAppStore((state) => state.setCurrentSession);
  const startSessionMutation = useStartSession();
  const activeSessionIds = useAppStore((state) => state.activeSessionIds);
  const thinkingSessionIds = useAppStore((state) => state.thinkingSessionIds);
  const unreadSessions = useAppStore((state) => state.unreadSessions);

  // Track which projects are expanded
  const [expandedProjects, setExpandedProjects] = useState<Set<string>>(new Set());

  const isLoading = sessionsLoading || projectsLoading;

  // Group sessions by project and limit to DEFAULT_SESSION_LIMIT
  const sessionsByProject = projects?.map((project) => {
    const projectSessions = sessions?.filter((session) => session.project_id === project.id) ?? [];
    // Sort sessions by creation date desc (assuming newer is more relevant)
    projectSessions.sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());

    const isExpanded = expandedProjects.has(project.id);
    const displayedSessions = isExpanded ? projectSessions : projectSessions.slice(0, DEFAULT_SESSION_LIMIT);
    const hasMore = projectSessions.length > DEFAULT_SESSION_LIMIT;

    return {
      ...project,
      sessions: projectSessions,
      displayedSessions,
      hasMore,
      isExpanded,
    };
  });

  const toggleProjectExpanded = (projectId: string) => {
    setExpandedProjects((prev) => {
      const newSet = new Set(prev);
      if (newSet.has(projectId)) {
        newSet.delete(projectId);
      } else {
        newSet.add(projectId);
      }
      return newSet;
    });
  };

  const handleSessionSelect = (sessionId: string) => {
    setCurrentSession(sessionId);

    // Auto-start the session if it's not already active
    const session = sessions?.find((s) => s.id === sessionId);
    if (session && !session.is_active) {
      startSessionMutation.mutate(sessionId);
    }
  };

  const getSessionDisplay = (session: Session) => {
    const isAutoName = isAutoGeneratedName(session.name);

    // If it's an auto-generated name, show the formatted date as title
    // and a shortened ID as subtitle for reference
    if (isAutoName) {
      return {
        title: formatDate(session.created_at),
        subtitle: `ID: ${session.id.substring(0, 8)}...`,
        icon: <Calendar className="h-3 w-3" />,
      };
    }

    // If it's a custom name, show it as title, and date as subtitle
    return {
      title: session.name || "Untitled Session",
      subtitle: formatDate(session.created_at),
      icon: <MessageSquare className="h-3 w-3" />,
    };
  };

  return (
    <div className={cn("flex flex-col h-full bg-background", className)} data-testid="session-list">
      {/* Header */}
      <div className="p-4 border-b flex items-center justify-between gap-2 bg-card text-card-foreground shadow-sm z-10" data-testid="session-list-header">
        <h2 className="text-xl font-heading font-bold tracking-wide">Sessions</h2>
        <div className="flex items-center gap-2">
          <ProjectManager />
          <NewSessionDialog />
        </div>
      </div>

      {isLoading && (
        <div className="flex-1 flex items-center justify-center text-muted-foreground font-body">
          <Loader2 className="h-5 w-5 animate-spin mr-2" />
          Loading...
        </div>
      )}

      {!isLoading && (
        /* Sessions list */
        <ScrollArea className="flex-1">
          <div className="p-3 space-y-4">
            {sessionsByProject?.map((project) => (
              <div key={project.id} className="space-y-1">
                {/* Project header with expand/collapse */}
                <button
                  onClick={() => toggleProjectExpanded(project.id)}
                  className={cn(
                    "w-full flex items-center gap-2 px-2 py-2 text-sm font-bold font-body tracking-wider",
                    "text-muted-foreground uppercase hover:text-foreground transition-colors",
                    "rounded-lg hover:bg-accent/20"
                  )}
                >
                  {project.isExpanded ? (
                    <ChevronDown className="h-4 w-4" />
                  ) : (
                    <ChevronRight className="h-4 w-4" />
                  )}
                  <span className="flex-1 text-left truncate">{project.name}</span>
                  <Badge variant="outline" className="text-xs font-mono">
                    {project.sessions.length}
                  </Badge>
                </button>

                {/* Project sessions */}
                {project.displayedSessions.length === 0 ? (
                  <div className="px-8 py-2 text-sm text-muted-foreground italic font-body">
                    No sessions
                  </div>
                ) : (
                  <ul className="space-y-2 mt-1 px-1">
                    {project.displayedSessions.map((session) => {
                      const { title, subtitle, icon } = getSessionDisplay(session);
                      return (
                        <li key={session.id}>
                          <button
                            onClick={() => handleSessionSelect(session.id)}
                            className={cn(
                              "w-full flex items-start gap-3 px-4 py-3 text-left rounded-wobbly transition-all",
                              "border border-transparent",
                              "hover:bg-accent/10 hover:border-border/50 hover:shadow-sm",
                              currentSessionId === session.id
                                ? "bg-accent text-accent-foreground shadow-hard-sm rotate-1 border-black/10 font-medium"
                                : "bg-card/50 text-card-foreground hover:rotate-[-0.5deg]"
                            )}
                            data-testid={`session-item-${session.id}`}
                          >
                            {/* Status indicator */}
                            <div className="relative mt-1.5 shrink-0">
                              {/* Active/inactive dot */}
                              {(activeSessionIds.has(session.id) || session.is_active) ? (
                                <span
                                  className="h-2.5 w-2.5 block rounded-full bg-green-500 shadow-[0_0_4px_theme(colors.green.400)]"
                                  aria-label="Active session"
                                />
                              ) : (
                                <span className="h-2.5 w-2.5 block rounded-full bg-muted-foreground/30" />
                              )}

                              {/* Thinking spinner overlay */}
                              {thinkingSessionIds.has(session.id) && (
                                <span className="absolute -top-1.5 -right-1.5">
                                  <Loader2 className="h-5 w-5 animate-spin text-primary" />
                                </span>
                              )}
                            </div>

                            {/* Session info */}
                            <div className="flex-1 min-w-0">
                              <div className="flex items-center gap-2 mb-0.5">
                                <span className="truncate font-body text-base leading-none">
                                  {title}
                                </span>
                                {unreadSessions.has(session.id) && (
                                  <span className="flex h-2 w-2 rounded-full bg-primary animate-pulse" />
                                )}
                              </div>

                              <div className="flex items-center gap-1 text-xs text-muted-foreground font-body">
                                {icon}
                                <span className="truncate">{subtitle}</span>
                              </div>
                            </div>
                          </button>
                        </li>
                      );
                    })}
                  </ul>
                )}

                {/* Show more/less button */}
                {project.hasMore && (
                  <div className="px-2 mt-2">
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => toggleProjectExpanded(project.id)}
                      className="w-full justify-start text-xs h-8 font-body text-muted-foreground hover:text-foreground"
                    >
                      {project.isExpanded ? (
                        <span>Show less ({DEFAULT_SESSION_LIMIT})</span>
                      ) : (
                        <span>Show {project.sessions.length - DEFAULT_SESSION_LIMIT} more...</span>
                      )}
                    </Button>
                  </div>
                )}
              </div>
            ))}

            {sessionsByProject?.length === 0 && (
              <div className="flex flex-col items-center justify-center py-10 text-center space-y-3 text-muted-foreground">
                <div className="h-12 w-12 rounded-full bg-muted/30 flex items-center justify-center">
                  <MessageSquare className="h-6 w-6 opacity-50" />
                </div>
                <p className="text-sm font-body">No projects found</p>
              </div>
            )}
          </div>
        </ScrollArea>
      )}
    </div>
  );
}
