import { useState } from "react";
import { useSessions } from "../hooks/useSessions";
import { useProjects } from "../hooks/useProjects";
import { useAppStore } from "../store/appStore";
import { ScrollArea } from "./ui/scroll-area";
import { NewSessionDialog } from "./NewSessionDialog";
import { ProjectManager } from "./ProjectManager";
import { Badge } from "./ui/badge";
import { Button } from "./ui/button";
import { Loader2, ChevronDown, ChevronRight, MessageSquare, Calendar, Settings, Plus } from "lucide-react";
import { cn } from "../lib/utils";
import type { Session } from "../types";

interface SessionListProps {
  className?: string;
}

const DEFAULT_SESSION_LIMIT = 5;

// Helper to check if a name matches the auto-generated timestamp pattern
// e.g., 2026-01-08T01-21-05-615Z_ed05b...
const isAutoGeneratedName = (name: string) => {
  return /^\d{4}-\d{2}-\d{2}T/.test(name);
};

const formatDate = (dateString: string) => {
  try {
    return new Intl.DateTimeFormat('en-US', {
      month: 'short',
      day: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
    }).format(new Date(dateString));
  } catch {
    return dateString;
  }
};

export function SessionList({ className }: SessionListProps) {
  const { data: sessions, isLoading: sessionsLoading } = useSessions();
  const { data: projects, isLoading: projectsLoading } = useProjects();
  const currentSessionId = useAppStore((state) => state.currentSessionId);
  const setCurrentSession = useAppStore((state) => state.setCurrentSession);
  const activeSessionIds = useAppStore((state) => state.activeSessionIds);
  const thinkingSessionIds = useAppStore((state) => state.thinkingSessionIds);
  const unreadSessions = useAppStore((state) => state.unreadSessions);

  // Track which projects are expanded
  const [expandedProjects, setExpandedProjects] = useState<Set<string>>(new Set());

  const isLoading = sessionsLoading || projectsLoading;

  // Group sessions by project and limit to DEFAULT_SESSION_LIMIT
  const sessionsByProject = projects?.map((project) => {
    const projectSessions = sessions?.filter((session) => session.project_id === project.id) ?? [];
    // Sort sessions by creation date desc (assuming newer is more relevant)
    projectSessions.sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());

    const isExpanded = expandedProjects.has(project.id);
    const displayedSessions = isExpanded ? projectSessions : projectSessions.slice(0, DEFAULT_SESSION_LIMIT);
    const hasMore = projectSessions.length > DEFAULT_SESSION_LIMIT;

    return {
      ...project,
      sessions: projectSessions,
      displayedSessions,
      hasMore,
      isExpanded,
    };
  });

  const toggleProjectExpanded = (projectId: string) => {
    setExpandedProjects((prev) => {
      const newSet = new Set(prev);
      if (newSet.has(projectId)) {
        newSet.delete(projectId);
      } else {
        newSet.add(projectId);
      }
      return newSet;
    });
  };

  const handleSessionSelect = (sessionId: string) => {
    // Just switch to the session, don't stop anything
    setCurrentSession(sessionId);
  };

  const getSessionDisplay = (session: Session) => {
    const isAutoName = isAutoGeneratedName(session.name);

    if (isAutoName) {
      return {
        title: formatDate(session.created_at),
        subtitle: `ID: ${session.id.substring(0, 8)}...`,
        icon: <Calendar className="h-3.5 w-3.5" />,
      };
    }

    return {
      title: session.name || "Untitled Session",
      subtitle: formatDate(session.created_at),
      icon: <MessageSquare className="h-3.5 w-3.5" />,
    };
  };

  return (
    <div className={cn("flex flex-col h-full bg-background", className)} data-testid="session-list">
      {/* Header - added pr-12 on mobile to avoid sheet close button */}
      <div className="p-4 border-b-2 flex items-center justify-between gap-2 bg-card text-card-foreground shadow-sm z-10 pr-12 md:pr-4" data-testid="session-list-header">
        <h2 className="text-2xl font-heading font-bold tracking-tight">Sessions</h2>
        <div className="flex items-center gap-2">
          <ProjectManager trigger={
            <Button
              variant="outline"
              size="icon"
              className="h-9 w-9 rounded-wobblyMd border-2 shadow-hard-sm bg-white hover:bg-muted transition-all"
              title="Manage Projects"
            >
              <Settings className="h-5 w-5" />
            </Button>
          } />
          <NewSessionDialog trigger={
            <Button
              variant="outline"
              size="icon"
              id="new-session-button"
              data-testid="new-session-button"
              className="h-9 w-9 rounded-wobblyMd border-2 shadow-hard-sm bg-white hover:bg-accent hover:text-accent-foreground transition-all group"
              title="New Session"
            >
              <Plus className="h-5 w-5 text-accent md:text-primary group-hover:text-accent-foreground transition-colors" />
            </Button>
          } />
        </div>
      </div>

      {isLoading && (
        <div className="flex-1 flex items-center justify-center text-muted-foreground font-body py-12">
          <Loader2 className="h-6 w-6 animate-spin mr-3" />
          <span className="text-lg">Loading...</span>
        </div>
      )}

      {!isLoading && (
        <ScrollArea className="flex-1">
          <div className="p-4 space-y-6">
            {sessionsByProject?.map((project) => (
              <div key={project.id} className="space-y-2">
                {/* Project header */}
                <button
                  onClick={() => toggleProjectExpanded(project.id)}
                  className={cn(
                    "w-full flex items-center gap-2 px-1 py-1 text-base font-bold font-heading",
                    "text-muted-foreground hover:text-foreground transition-colors group"
                  )}
                >
                  <div className="bg-muted/50 p-1 rounded-wobblyMd border-2 border-transparent group-hover:border-primary/30 transition-all">
                    {project.isExpanded ? (
                      <ChevronDown className="h-4 w-4" />
                    ) : (
                      <ChevronRight className="h-4 w-4" />
                    )}
                  </div>
                  <span className="flex-1 text-left truncate">{project.name}</span>
                  <Badge variant="outline" className="text-xs font-mono border-2 bg-background">
                    {project.sessions.length}
                  </Badge>
                </button>

                {/* Project sessions */}
                {project.displayedSessions.length === 0 ? (
                  <div className="px-8 py-3 text-sm text-muted-foreground italic font-body border-2 border-dashed rounded-lg opacity-60">
                    No sessions yet
                  </div>
                ) : (
                  <ul className="space-y-3 mt-2">
                    {project.displayedSessions.map((session) => {
                      const { title, subtitle, icon } = getSessionDisplay(session);
                      const isActive = activeSessionIds.has(session.id) || session.is_active;
                      const isThinking = thinkingSessionIds.has(session.id);
                      const isSelected = currentSessionId === session.id;

                      return (
                        <li key={session.id}>
                          <button
                            onClick={() => handleSessionSelect(session.id)}
                            className={cn(
                              "w-full flex items-start gap-4 px-4 py-3 text-left rounded-wobblyMd transition-all",
                              "border-2",
                              isSelected
                                ? "bg-accent text-accent-foreground shadow-hard border-primary rotate-1 font-medium z-10 relative"
                                : "bg-card border-transparent hover:border-primary/50 hover:shadow-hard-sm hover:rotate-[0.5deg] active:scale-[0.98]"
                            )}
                            data-testid={`session-item-${session.id}`}
                          >
                            {/* Status indicator */}
                            <div className="relative mt-1 shrink-0">
                              <div className={cn(
                                "h-3 w-3 rounded-full border border-black/10",
                                isActive ? "bg-green-500 shadow-[0_0_8px_theme(colors.green.400)]" : "bg-muted-foreground/20"
                              )} />

                              {isThinking && (
                                <span className="absolute -top-2 -right-2 bg-background rounded-full p-0.5 shadow-sm">
                                  <Loader2 className="h-4 w-4 animate-spin text-primary" />
                                </span>
                              )}
                            </div>

                            {/* Session info */}
                            <div className="flex-1 min-w-0">
                              <div className="flex items-center justify-between gap-2 mb-1">
                                <span className={cn(
                                  "truncate font-heading text-lg leading-tight",
                                  isSelected ? "text-accent-foreground" : "text-foreground"
                                )}>
                                  {title}
                                </span>
                                {unreadSessions.has(session.id) && (
                                  <Badge className="h-4 w-4 p-0 rounded-full bg-accent hover:bg-accent flex items-center justify-center animate-pulse border-none shadow-none">
                                    <span className="sr-only">Unread</span>
                                  </Badge>
                                )}
                              </div>

                              <div className={cn(
                                "flex items-center gap-1.5 text-sm font-body",
                                isSelected ? "text-accent-foreground/80" : "text-muted-foreground"
                              )}>
                                <span className="shrink-0">{icon}</span>
                                <span className="truncate">{subtitle}</span>
                              </div>
                            </div>
                          </button>
                        </li>
                      );
                    })}
                  </ul>
                )}

                {/* Show more/less button */}
                {project.hasMore && (
                  <div className="pt-2">
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => toggleProjectExpanded(project.id)}
                      className="w-full justify-center text-sm h-10 font-heading tracking-wide text-muted-foreground hover:text-foreground hover:bg-muted/30 rounded-lg border-2 border-dashed border-muted/50 transition-all"
                    >
                      {project.isExpanded ? (
                        <span>Show less</span>
                      ) : (
                        <span>Show {project.sessions.length - DEFAULT_SESSION_LIMIT} more...</span>
                      )}
                    </Button>
                  </div>
                )}
              </div>
            ))}

            {sessionsByProject?.length === 0 && (
              <div className="flex flex-col items-center justify-center py-16 text-center space-y-4 text-muted-foreground bg-muted/5 rounded-2xl border-2 border-dashed">
                <div className="h-16 w-16 rounded-full bg-muted/20 flex items-center justify-center">
                  <MessageSquare className="h-8 w-8 opacity-40" />
                </div>
                <div className="space-y-1">
                  <p className="text-xl font-heading font-bold">No projects yet!</p>
                  <p className="text-sm font-body px-8">Add a folder or project to start your first coding session.</p>
                </div>
                <NewSessionDialog trigger={
                  <Button className="rounded-wobblyMd border-2 shadow-hard-sm">
                    Get Started
                  </Button>
                } />
              </div>
            )}
          </div>
        </ScrollArea>
      )}
    </div>
  );
}

